# This is a basic workflow to help you get started with Actions
name: Example workflow

# Controls when the workflow will run
on:
  push:

jobs:
  hello:
    steps:
      - run: echo "Hello, World"
      - run: |
          echo look ma
          echo I'm a two-liner!
